# Generated by Django 6.0.3 on 2026-03-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dictionary', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='term',
            name='description',
        ),
        migrations.AddField(
            model_name='term',
            name='description_en',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='term',
            name='description_ru',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='term',
            name='description_uz',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='name_en',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='name_ru',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='name_uz',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
